### ISSUE TITLE
[Feature] Purge pagefile.sys completely

### ISSUE THREAD

**Issue by mrrezaie** [henrypp/memreduct#213]
Hi, it seems that memreduct doesn't clean pagefile.sys yet. It would be great if you add this feature. Highly applicable!!! Thank you in advance.

**Comment by techgamers2** [comment]
u can set to delete pagefile at every shutdown via registry 
source: [elevenforums](https://www.elevenforum.com/t/enable-or-disable-clear-virtual-memory-paging-file-at-shutdown-in-windows-11.8637/#Two)
``Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management]
"ClearPageFileAtShutdown"=dword:00000001``

**Comment by mrrezaie** [comment]
Thanks for your response. Yes, I had enabled this, but I was looking for a way to do that without system restart. Do you think that it is possible?

**Comment by mrrezaie** [comment]
Thanks again, I see your points. I need it because I work with some python codes that consume too much RAM (and hence pagefile) but do not purge it after finishing/closing and it leads to system instability (perhaps memory leak issue of a particular module). I wonder if some workaround exists.

**Comment by Initial-heart-1** [comment]
> Thanks again, I see your points. I need it because I work with some python codes that consume too much RAM (and hence pagefile) but do not purge it after finishing/closing and it leads to system instability (perhaps memory leak issue of a particular module). I wonder if some workaround exists.

_Try to disable pagefiles only when you run out of hard disk space._

It looks like Windows manages size of pagefile automatically, so u don't need to worry about clearing it manually if u don't restart or shutdown your computer.
If ur running out of space, it's better to **check for memory leaks** than to try to clear pagefile.
Clearing pagefile is mainly done to protect your RAM data from malicious read out that could occur rather than to free up hardisk space. (If not how does WinServer run no-downtime?)
If ur having trouble preventing memory leaks, u might want to consider upgrading your hardisk or RAM.

**Comment by mrrezaie** [comment]
Fair enough, thanks for your response. I have 6GB RAM and HDD, so pagefile is essential. 

Feel free to close this Issue if nothing can be done about it. Thanks again.
