### ISSUE TITLE
[Question]Why does the automatic memory clearing function fail every time the computer restarts and need to be manually clicked to clear before it takes effect

### ISSUE THREAD

**Issue by CaoJ20132014** [henrypp/memreduct#220]
Describe the question with as much detail as possible.

---

App version: 3.4
Windows version: Windows 11 家庭中文版23H2（22631.3374）

Why does the automatic memory clearing function fail every time the computer restarts and need to be manually clicked to clear before it takes effect

**Comment by Initial-heart-1** [comment]
_As the users display language is Chinese, I will reply in Chinese. Pls use Google Translate for details._
你好，看起来你似乎是一位中文用户，所以我使用中文回答你的问题。
请注意你应当提供一些关于这个问题的日志，而不是将一个问句摆出来而没有更多的有效信息，哪怕只是一张截图或是对情况仔细的描述也好。
看起来这不像是 memreduct 的问题，或许您可以检查 memreduct 是否可以正确的开机自启，以及检查 memreduct 是否有权限操作硬盘上的文件。
建议补充更多信息。

**Comment by kevincatenazzo** [comment]
I have the same issue, as soon i boot the PC, Mem Reduct won't start cleaning until i unlock admin rights, by opening the program. 
![Screenshot 2024-06-26 191733](https://github.com/henrypp/memreduct/assets/153632581/fc43c86d-fe18-4cee-a2e9-591b5132ed4b)

**Comment by BigBlueBaby** [comment]
我也遇到过这个问题，如果你的清理内存按钮上有管理员图标的话，应该是因为没有通过管理员运行，在我通过管理员运行过一次软件之后，就可以自动清理了
"I have also encountered this issue. If there is an administrator icon on your clear memory button, it might be because the program wasn't run as an administrator. After I ran the software once as an administrator, it could automatically clear the memory."

**Comment by henrypp** [comment]
you need to enable "Skip UAC option"
