### ISSUE TITLE
[Question] How do Memreduct works?

### ISSUE THREAD

**Issue by MRSEEO** [henrypp/memreduct#238]
Describe the question with as much detail as possible.

It is very interesting how exactly Memreduct works. The program consists of, say, one file, but it does useful work that Windows cannot do. Can you please explain how do this exactly works?
---

App version: 3.4
Windows version: Windows 10

**Comment by Initial-heart-1** [comment]
"The program used undocumented internal system features (Native API) to clear system cache (system working set, working set, standby page lists, modified page lists) with variable result ~10-50%. Application it is compatible with Windows XP SP3 and higher operating systems, but some general features available only since Windows Vista."(README)
for more info pls read source code

**Comment by MRSEEO** [comment]
> "The program used undocumented internal system features (Native API) to clear system cache (system working set, working set, standby page lists, modified page lists) with variable result ~10-50%. Application it is compatible with Windows XP SP3 and higher operating systems, but some general features available only since Windows Vista."(README) for more info pls read source code

Thank you!
