### ISSUE TITLE
Minimized Option

### ISSUE THREAD

**Issue by MrKlatuu** [henrypp/memreduct#37]
Why was the Start Minimized option removed?  I far preferred this to the full window when I launch this program.  Great program otherwise.

**Comment by henrypp** [comment]
There is only way to start minimized is set "/minimized" argument to the main executable. Auto-start is always minimized.

**Comment by QueenOfStars** [comment]
I don't understand why you closed the issue, this is a bug. :( 
I run Memreduct as portable and there's no safe way to set an argument to the main executable for a portable app, especially if it's launched from a portable suite like Portableapps. Auto-start is not an option because it's a portable app. I'll have to rollback to version 3.2 until you fix this.

**Comment by henrypp** [comment]
@QueenOfStars, Mem Reduct portable itself, and does not required use any frameworks.

**Comment by QueenOfStars** [comment]
@henrypp I think you are missing the point. Forget the launcher I'm using. When Mem Reduct is portable you can't have a standard shortcut with "/minimized" as an argument because USB drives don't have the same drive letter in all systems. I need the application to do its thing quietly in the background even when it'a portable, like in previous versions. Therefore this is a bug.

**Comment by hairycactus** [comment]
@henrypp
If possible, I would also prefer that Mem Reduct (portable build) is able to launch minimized to the system tray, but without having to use the new `/minimized` command-line parameter or shortcut (which itself does not permit relative paths).

Is there a technical reason why the previously-working option `StartMinimized` in `memreduct.ini` & the GUI was removed ?

The option last worked in: v3.2.1 (30 Jul 2017), & has no effect in:
- v3.3.1 (05 Jan 2018)
- v3.3 (19 Oct 2017)
- v3.2.2 (09 Sep 2017)

>henrypp:  [Auto-start is always minimized](https://github.com/henrypp/memreduct/issues/37#issuecomment-337344874).

Even though Mem Reduct always launches minimized if set to load with system startup (INI option: `AutorunIsEnabled=true`), this is not very useful when Mem Reduct is used as a portable.

**Scenario 1:**
When we use Mem Reduct from the USB thumbdrive on somebody's PC or a public library PC, we just plugin & launch the application, instead of rebooting the PC. (Even if we reboot the PC, we are also unlikely to know the login username & password.)

**Scenario 2:**
Setting Mem Reduct to auto-load with the system startup causes it to write to the registry at the below key. This is not possible when the user lacks admin rights. (The registry key's permissions is _Read-Only_ for non-admin users.)

```
HKCU\Software\Microsoft\Windows\CurrentVersion\Run
    Mem Reduct = "<FullPath>\memreduct.exe" /minimized   [REG_SZ]
```

Thanks !

**Comment by QueenOfStars** [comment]
@henrypp thank you for reverting this change in v3.3.2, much appreciated. So happy I can upgrade to the latest version and enjoy all improvements. Thank you for your hard work.

**Comment by hairycactus** [comment]
@henrypp
Thanks for reinstating the _'Start Minimized'_ option in Mem Reduct [v3.3.2](url=https://github.com/henrypp/memreduct/releases/download/v.3.3.2) (09 Feb 2018). Tested & working fine in Win 7 x64.
