### ISSUE TITLE
mem reduct auto cleaning issue on windows 10 - options greyed out in win10?

### ISSUE THREAD

**Issue by 0lm** [henrypp/memreduct#96]
hi there
i used mem reduct on a win 7 pc in the past and auto cleaning could always be set without problems (example: auto clean memory when 80% usage is reached).
but now i noticed on win 10, the settings about auto cleaning in the setting menu are all greyed out and i have no idea how to activate them

**Comment by DavidStafford1992** [comment]
To add onto this, as I think I'm experiencing the same/similar issue. The program does indeed seem to occasionally stop auto-cleaning and sort of just 'locks up'

For example today, I was wondering why my PC was so slow, I checked Mem Reduct, and all options were greyed, as seen here:
![2020-06-29 17_59_36-Task Manager](https://user-images.githubusercontent.com/61253693/86041599-2a659980-ba46-11ea-906d-c71a63e80e61.jpg)

I then clicked on 'Clean memory' manually, which then 'unlocked' the program, the options no longer being grey:
![2020-06-29 18_01_00-Settings](https://user-images.githubusercontent.com/61253693/86041702-584ade00-ba46-11ea-870d-65623e434462.jpg)

This kind of thing has happened in the past before, since when Mem Reduct is not working, I can feel the PC is slower than usual, and when I check Mem Reduct, the options have for some reason become grey... so yeah, something is definitely not as it should be.

**Comment by DavidStafford1992** [comment]
@0lm By the way, can you correct the title of the thread to something more presentable please? I strongly suggest renaming it to 
"Mem Reduct auto-cleaning issue on Windows 10"

**Comment by DavidStafford1992** [comment]
This still an issue...

**Comment by DavidStafford1992** [comment]
Okay, so the dev obviously doesn't care about this one bit whatsoever. I suggest switching to RAMRush

**Comment by 0lm** [comment]
it has been a while since i looked in here, sorry. i found out how to solve the issue.
it seems like it is an issue with windows 10. to make the greyed out options available, you have to start Mem Reduct as an Admin in Windows 10. (so basically, create a shortcut for mem reduct, right click and go to advanced, enable "run as admin". then the shortcut should run it always as admin. not sure how to add it as auto-admin into autostart.

**Comment by DavidStafford1992** [comment]
@0lm I see, I'm on an admin account myself, but yeah, makes sense I guess, as I've experienced similar with other programs, in the past... perhaps it'd be possible to elevate something like NirCmd, on start-up

**Comment by 0lm** [comment]
> 
> 
> @0lm I see, I'm on an admin account myself, but yeah, makes sense I guess, as I've experienced similar with other programs, in the past... perhaps it'd be possible to elevate something like NirCmd, on start-up

And to be fair, in the description on henry++ website he actually says this: `"You can download either the installer or portable version. For correct working, need administrator rights."` (i saw that later, after i already found out the solution for my problem. but yes, the solution was already on his website)
but still it wondered my why no one responded here lol. well but since it is solved now, i think it is not a bug, but ist just needs admin right in windows 10. so i will better close this (i changed the title btw, so other users can find it easier when searching)

**Comment by HeadYolk** [comment]
bro if you have an admin icon in your Clean Memory icon uninstall that, instead download the "[memreduct-3.4-setup.exe]" at https://www.henrypp.org/product/memreduct instead of the other options, then copy my general setting..... 
![Screenshot (9)](https://user-images.githubusercontent.com/101549530/158125307-ba6e2bb1-2b4c-4b1b-bec8-6f99d29ed625.png)

(Sorry If My English is Bad)

**Comment by oSmartCoder** [comment]
That's because you need to run it as an administrator for it to access certain things.
